/* ════════════════════════════════════════════════════════════════════ *\
                            mainpro.h

                 Sheduler`s multi-process  library

                        (C)  Kaling N.V. 1994

\* ════════════════════════════════════════════════════════════════════ */

#if     !defined(__MAINPOC_H)
#define __MAINPOC_H

extern  void                    debQ();
extern  void                    debW();
extern  void                    debE();
extern  void                    debR();

#endif  /* __MAINPOC_H */

/* ════════════════════════════════════════════════════════════════════ */






